<?php
// pre_checks/country_codes.php
// Static lookup for all countries: ISO → Country → Dial Code

return [
    "AF" => ["country" => "Afghanistan", "dial_code" => "93"],
    "AL" => ["country" => "Albania", "dial_code" => "355"],
    "DZ" => ["country" => "Algeria", "dial_code" => "213"],
    "AS" => ["country" => "American Samoa", "dial_code" => "1684"],
    "AD" => ["country" => "Andorra", "dial_code" => "376"],
    "AO" => ["country" => "Angola", "dial_code" => "244"],
    "AI" => ["country" => "Anguilla", "dial_code" => "1264"],
    "AG" => ["country" => "Antigua and Barbuda", "dial_code" => "1268"],
    "AR" => ["country" => "Argentina", "dial_code" => "54"],
    "AM" => ["country" => "Armenia", "dial_code" => "374"],
    "AW" => ["country" => "Aruba", "dial_code" => "297"],
    "AU" => ["country" => "Australia", "dial_code" => "61"],
    "AT" => ["country" => "Austria", "dial_code" => "43"],
    "AZ" => ["country" => "Azerbaijan", "dial_code" => "994"],
    "BS" => ["country" => "Bahamas", "dial_code" => "1242"],
    "BH" => ["country" => "Bahrain", "dial_code" => "973"],
    "BD" => ["country" => "Bangladesh", "dial_code" => "880"],
    "BB" => ["country" => "Barbados", "dial_code" => "1246"],
    "BY" => ["country" => "Belarus", "dial_code" => "375"],
    "BE" => ["country" => "Belgium", "dial_code" => "32"],
    "BZ" => ["country" => "Belize", "dial_code" => "501"],
    "BJ" => ["country" => "Benin", "dial_code" => "229"],
    "BM" => ["country" => "Bermuda", "dial_code" => "1441"],
    "BT" => ["country" => "Bhutan", "dial_code" => "975"],
    "BO" => ["country" => "Bolivia", "dial_code" => "591"],
    "BA" => ["country" => "Bosnia and Herzegovina", "dial_code" => "387"],
    "BW" => ["country" => "Botswana", "dial_code" => "267"],
    "BR" => ["country" => "Brazil", "dial_code" => "55"],
    "BN" => ["country" => "Brunei", "dial_code" => "673"],
    "BG" => ["country" => "Bulgaria", "dial_code" => "359"],
    "BF" => ["country" => "Burkina Faso", "dial_code" => "226"],
    "BI" => ["country" => "Burundi", "dial_code" => "257"],
    "KH" => ["country" => "Cambodia", "dial_code" => "855"],
    "CM" => ["country" => "Cameroon", "dial_code" => "237"],
    "CA" => ["country" => "Canada", "dial_code" => "1"],
    "CV" => ["country" => "Cape Verde", "dial_code" => "238"],
    "KY" => ["country" => "Cayman Islands", "dial_code" => "1345"],
    "CF" => ["country" => "Central African Republic", "dial_code" => "236"],
    "TD" => ["country" => "Chad", "dial_code" => "235"],
    "CL" => ["country" => "Chile", "dial_code" => "56"],
    "CN" => ["country" => "China", "dial_code" => "86"],
    "CO" => ["country" => "Colombia", "dial_code" => "57"],
    "KM" => ["country" => "Comoros", "dial_code" => "269"],
    "CG" => ["country" => "Congo", "dial_code" => "242"],
    "CR" => ["country" => "Costa Rica", "dial_code" => "506"],
    "HR" => ["country" => "Croatia", "dial_code" => "385"],
    "CU" => ["country" => "Cuba", "dial_code" => "53"],
    "CY" => ["country" => "Cyprus", "dial_code" => "357"],
    "CZ" => ["country" => "Czech Republic", "dial_code" => "420"],
    "DK" => ["country" => "Denmark", "dial_code" => "45"],
    "DJ" => ["country" => "Djibouti", "dial_code" => "253"],
    "DM" => ["country" => "Dominica", "dial_code" => "1767"],
    "DO" => ["country" => "Dominican Republic", "dial_code" => "1809"],
    "EC" => ["country" => "Ecuador", "dial_code" => "593"],
    "EG" => ["country" => "Egypt", "dial_code" => "20"],
    "SV" => ["country" => "El Salvador", "dial_code" => "503"],
    "GQ" => ["country" => "Equatorial Guinea", "dial_code" => "240"],
    "ER" => ["country" => "Eritrea", "dial_code" => "291"],
    "EE" => ["country" => "Estonia", "dial_code" => "372"],
    "ET" => ["country" => "Ethiopia", "dial_code" => "251"],
    "FJ" => ["country" => "Fiji", "dial_code" => "679"],
    "FI" => ["country" => "Finland", "dial_code" => "358"],
    "FR" => ["country" => "France", "dial_code" => "33"],
    "DE" => ["country" => "Germany", "dial_code" => "49"],
    "GH" => ["country" => "Ghana", "dial_code" => "233"],
    "GR" => ["country" => "Greece", "dial_code" => "30"],
    "HK" => ["country" => "Hong Kong", "dial_code" => "852"],
    "IN" => ["country" => "India", "dial_code" => "91"],
    "ID" => ["country" => "Indonesia", "dial_code" => "62"],
    "IR" => ["country" => "Iran", "dial_code" => "98"],
    "IQ" => ["country" => "Iraq", "dial_code" => "964"],
    "IE" => ["country" => "Ireland", "dial_code" => "353"],
    "IL" => ["country" => "Israel", "dial_code" => "972"],
    "IT" => ["country" => "Italy", "dial_code" => "39"],
    "JM" => ["country" => "Jamaica", "dial_code" => "1876"],
    "JP" => ["country" => "Japan", "dial_code" => "81"],
    "JO" => ["country" => "Jordan", "dial_code" => "962"],
    "KZ" => ["country" => "Kazakhstan", "dial_code" => "7"],
    "KE" => ["country" => "Kenya", "dial_code" => "254"],
    "KR" => ["country" => "South Korea", "dial_code" => "82"],
    "KW" => ["country" => "Kuwait", "dial_code" => "965"],
    "LB" => ["country" => "Lebanon", "dial_code" => "961"],
    "MY" => ["country" => "Malaysia", "dial_code" => "60"],
    "MV" => ["country" => "Maldives", "dial_code" => "960"],
    "MX" => ["country" => "Mexico", "dial_code" => "52"],
    "MA" => ["country" => "Morocco", "dial_code" => "212"],
    "NP" => ["country" => "Nepal", "dial_code" => "977"],
    "NL" => ["country" => "Netherlands", "dial_code" => "31"],
    "NZ" => ["country" => "New Zealand", "dial_code" => "64"],
    "NG" => ["country" => "Nigeria", "dial_code" => "234"],
    "NO" => ["country" => "Norway", "dial_code" => "47"],
    "OM" => ["country" => "Oman", "dial_code" => "968"],
    "PK" => ["country" => "Pakistan", "dial_code" => "92"],
    "PH" => ["country" => "Philippines", "dial_code" => "63"],
    "PL" => ["country" => "Poland", "dial_code" => "48"],
    "PT" => ["country" => "Portugal", "dial_code" => "351"],
    "QA" => ["country" => "Qatar", "dial_code" => "974"],
    "RO" => ["country" => "Romania", "dial_code" => "40"],
    "RU" => ["country" => "Russia", "dial_code" => "7"],
    "SA" => ["country" => "Saudi Arabia", "dial_code" => "966"],
    "SG" => ["country" => "Singapore", "dial_code" => "65"],
    "ZA" => ["country" => "South Africa", "dial_code" => "27"],
    "ES" => ["country" => "Spain", "dial_code" => "34"],
    "LK" => ["country" => "Sri Lanka", "dial_code" => "94"],
    "SE" => ["country" => "Sweden", "dial_code" => "46"],
    "CH" => ["country" => "Switzerland", "dial_code" => "41"],
    "TR" => ["country" => "Turkey", "dial_code" => "90"],
    "UA" => ["country" => "Ukraine", "dial_code" => "380"],
    "AE" => ["country" => "United Arab Emirates", "dial_code" => "971"],
    "GB" => ["country" => "United Kingdom", "dial_code" => "44"],
    "US" => ["country" => "United States", "dial_code" => "1"],
    "VN" => ["country" => "Vietnam", "dial_code" => "84"],
    "ZM" => ["country" => "Zambia", "dial_code" => "260"],
    "ZW" => ["country" => "Zimbabwe", "dial_code" => "263"],
];
